<?xml version="1.0" encoding="utf-8"?><Database Name="ALGO_TRADER" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FOOFVALVE-PC\DOSHALGO;Initial Catalog=ALGO_TRADER;Integrated Security=True" SettingsObjectName="Stuff.Properties.Settings" SettingsPropertyName="ALGO_TRADERConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.END_OF_DAY" Member="END_OF_DAYs">
    <Type Name="END_OF_DAY">
      <Column Name="SecurityCode" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OpeningPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="HighPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="LowPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ClosingPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>